name: BuildAndPublish

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'RecurrenceCalculator.sln'
    
    runs-on: ubuntu-latest
    
    permissions:
      id-token: write
      contents: read
      
    steps:
      - uses: actions/checkout@v2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        with: 
          nuget-version: latest

      - name: Restore dependencies
        working-directory: ./RecurrenceCalculator
        run: dotnet restore $SOLUTION

      - name: Build
        working-directory: ./RecurrenceCalculator
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG --no-restore

      - name: Run tests
        working-directory: ./RecurrenceCalculator
        run: dotnet test $SOLUTION --configuration $BUILD_CONFIG --no-restore --no-build --verbosity normal

      - name: NuGet login (OIDC → temp API key)
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
          
      - name: Push to nuget
        working-directory: ./RecurrenceCalculator
        run: dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{steps.login.outputs.NUGET_API_KEY}}       
